Repository Team14SNS/Philogram, pull requests merged in 2023-08, with the labels that each got.

#32 [Feature]detail-page
  app/src/main/java/com/example/philogram/DetailActivity.kt
  app/src/main/java/com/example/philogram/FeedActivity.kt
  app/src/main/java/com/example/philogram/TestData.kt
  app/src/main/java/com/example/philogram/main/MainActivity.kt
  app/src/main/java/com/example/philogram/main/MainPostItem.kt
  app/src/main/res/layout/activity_detail.xml
Labels: feature

#34 Design: 디자인 수정
  app/src/main/res/layout-land/activity_detail.xml
  app/src/main/res/layout-land/activity_feed.xml
  app/src/main/res/layout-land/activity_main.xml
  app/src/main/res/layout-land/activity_my_page_edit.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_feed.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_my_page_edit.xml
  app/src/main/res/layout/item_main_post.xml
  app/src/main/res/layout/item_main_profile.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: design

#35 Feature/detail edit
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/philogram/DetailActivity.kt
  app/src/main/java/com/example/philogram/MyPageEditActivity.kt
  app/src/main/java/com/example/philogram/User.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/values/themes.xml
Labels: feature

#36 [FEAT]비밀번호재설정 페이지 기능 추가
  app/src/main/java/com/example/philogram/LoginFindPwActivity.kt
Labels: feature

#37 FEAT: 로그 아웃 기능 추가
  app/src/main/java/com/example/philogram/DetailActivity.kt
  app/src/main/java/com/example/philogram/MyPageEditActivity.kt
  app/src/main/java/com/example/philogram/TestData.kt
  app/src/main/res/drawable/baseline_cancel_24.xml
  app/src/main/res/drawable/dialog_rounded_border.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/dialog_logout.xml
  app/src/main/res/values/strings.xml
Labels: feature

#38 수정페이지 imageview 확인
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/philogram/MyPageEditActivity.kt
  app/src/main/res/layout-land/activity_my_page_edit.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_my_page_edit.xml
Labels: feature

#40 DESIGN:가로모드 레이아웃 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/philogram/LoginFindPwActivity.kt
  app/src/main/res/drawable/ic_logo.xml
  app/src/main/res/layout-land/activity_login.xml
  app/src/main/res/layout-land/activity_login_find_pw.xml
  app/src/main/res/layout-land/activity_my_page_edit.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_login_find_pw.xml
  app/src/main/res/layout/activity_my_page_edit.xml
Labels: design

#41 [Feature] main page
  app/build.gradle
  app/src/main/java/com/example/philogram/DetailActivity.kt
  app/src/main/java/com/example/philogram/main/MainActivity.kt
  app/src/main/res/drawable-night/ic_edit.xml
  app/src/main/res/drawable-night/ic_logout.xml
  app/src/main/res/drawable/dialog_rounded_border.xml
  app/src/main/res/drawable/ic_back_pressed.xml
  app/src/main/res/drawable/ic_back_pressed_selector.xml
  app/src/main/res/drawable/ic_cancel.xml
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/drawable/ic_edit_pressed.xml
  app/src/main/res/drawable/ic_edit_pressed_selector.xml
  app/src/main/res/drawable/ic_logout.xml
  app/src/main/res/drawable/ic_logout_pressed.xml
  app/src/main/res/drawable/ic_logout_pressed_selector.xml
  app/src/main/res/drawable/ic_mypage_pressed.xml
  app/src/main/res/drawable/ic_mypage_pressed_selector.xml
  app/src/main/res/layout-land/activity_detail.xml
  app/src/main/res/layout-land/activity_feed.xml
  app/src/main/res/layout-land/activity_main.xml
  app/src/main/res/layout-land/activity_my_page_edit.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_feed.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_my_page_edit.xml
  app/src/main/res/layout/dialog_image_popup.xml
  app/src/main/res/layout/dialog_logout.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: feature

#42 [FEAT] : translate
  .idea/misc.xml
  .idea/vcs.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/philogram/LoginActivity.kt
  app/src/main/java/com/example/philogram/main/MainActivity.kt
  app/src/main/res/drawable/main.png
  app/src/main/res/layout-land/activity_detail.xml
  app/src/main/res/layout-land/activity_login.xml
  app/src/main/res/layout-land/activity_login_find_pw.xml
  app/src/main/res/layout-land/activity_main.xml
  app/src/main/res/layout-land/activity_my_page_edit.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_login_find_pw.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_my_page_edit.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/locales_config.xml
  build.gradle
Labels: feature

#43 FEAT: 수정페이지 image 맞춤
  .idea/deploymentTargetDropDown.xml
  app/src/main/res/layout-land/activity_my_page_edit.xml
  app/src/main/res/layout/activity_my_page_edit.xml
Labels: feature

#44 [README]추가
  README.md
Labels: docs

#45 Refactoring
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/philogram/DetailActivity.kt
  app/src/main/java/com/example/philogram/FeedActivity.kt
  app/src/main/java/com/example/philogram/FeedManager.kt
  app/src/main/java/com/example/philogram/LoginActivity.kt
  app/src/main/java/com/example/philogram/LoginFindPwActivity.kt
  app/src/main/java/com/example/philogram/MyPageEditActivity.kt
  app/src/main/java/com/example/philogram/SignupActivity.kt
  app/src/main/java/com/example/philogram/UserManager.kt
  app/src/main/java/com/example/philogram/main/MainActivity.kt
  app/src/main/res/layout-land/activity_detail.xml
  app/src/main/res/layout-land/activity_login.xml
  app/src/main/res/layout-land/activity_login_find_pw.xml
  app/src/main/res/layout-land/activity_main.xml
  app/src/main/res/layout-land/activity_my_page_edit.xml
  app/src/main/res/layout-land/activity_signup.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_login_find_pw.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_my_page_edit.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/dialog_logout.xml
  app/src/main/res/layout/item_main_post.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#47 README: 내용 추가
  README.md
Labels: feature

#49 font 크기 별 자동 적용 기능 구현
  app/src/main/java/com/example/philogram/FeedActivity.kt
  app/src/main/java/com/example/philogram/main/MainActivity.kt
  app/src/main/res/layout-land/activity_detail.xml
  app/src/main/res/layout-land/activity_login.xml
  app/src/main/res/layout-land/activity_login_find_pw.xml
  app/src/main/res/layout-land/activity_main.xml
  app/src/main/res/layout-land/activity_my_page_edit.xml
  app/src/main/res/layout-land/activity_signup.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_login_find_pw.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_my_page_edit.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/dialog_logout.xml
  app/src/main/res/layout/item_main_post.xml
Labels: feature
